Update run profiles
flipkart-incubator/varadhi pull request #160
Opened 2024-08-06 03:49 UTC by iosdev747

PR changes:
- add dependency stack run and app run profiles
- ignore any run profile changes
- update readme with new profiles

PS: I also tried adding references to the run profiles in readme so IntelliJ can detect them and can be run directly from readme (https://www.jetbrains.com/help/idea/markdown.html#run-commands). Making user friendly first time setup. But detection is not working for profiles.

2024-08-08 17:33 UTC, kmrdhruv requested changes

2024-08-12 06:55 UTC, iosdev747 commented on .run/varadhi local [run].run.xml
> +    <ExternalSystemSettings>
Will use whats configured in project platform SDK.

2024-08-13 14:28 UTC, iosdev747 commented on .run/varadhi local [run].run.xml
> +      <option name="vmOptions" />
Added both, and btw for `src/main/resources/log4j2.xml` its being auto picked.

2024-08-16 05:17 UTC, kmrdhruv approved these changes
LGTM

2024-08-21 13:15 UTC, merged