Add python script for zookeeper benchmark
flipkart-incubator/varadhi pull request #27
Opened 2023-06-27 08:18 UTC by aayustark007-fk

This script connects to zookeeper ensemble, loads data under a parent node and then measures the response time of get_children() call.

Various parameters are configurable and can be fetched by running `python zk_benchmark.py -h`
To speed up data loading, there are two options, multi-threaded dataloader and multi-process dataloader. Multi-process dataloader has some bugs so its not enabled by default.

Requirements: python 3.10+, tqdm, kazoo

2023-06-28 14:07 UTC, kmrdhruv commented on scripts/zk_benchmark.py
> +        with DataLoader(self.config, zk_config=self.zk_config) as loader:
is this creating threadpool in processpool, expected ?

2023-06-28 14:08 UTC, kmrdhruv commented on scripts/zk_benchmark.py
> +    def __get_chunked_configs(self, child_node_config: ChildNodeConfig) -> list[ChildNodeConfig]:
with default chunk_size of 10K, and target range of 10K, this will effectively generate single block ?
should default be smaller number say 1K ?

2023-06-28 14:36 UTC, kmrdhruv commented on scripts/zk_benchmark.py
> +            name_res = "{}_{}".format(name, str(gen + 1))
this wouldn't take care of name length requirements, but that should be fine in case fixed name is needed. just add a comment for the same.

2023-06-28 14:45 UTC, kmrdhruv commented on scripts/zk_benchmark.py
> +                print("Latency get_children on path {}: {} ms".format(path, t.time / measure_samples))
in this case it wouldn't matter much, but it would be good to have it as min, max, avg  over the sample range.

2023-06-28 15:03 UTC, kmrdhruv requested changes
move this to scripts/benchmarks directory and also add a small readme under same folder on how to install dependencies and run the benchmark as well.

2023-06-30 09:46 UTC, aayustark007-fk commented on scripts/zk_benchmark.py
> +            for future in concurrent.futures.as_completed(futures_to_id):
the API for multiprocess executor does not provide a way to pass timeout
trying to find a way to pass sigterm to subprocesses

2023-07-03 10:57 UTC, kmrdhruv commented on scripts/zk_benchmark.py
> +            for future in concurrent.futures.as_completed(futures_to_id):
may be kill process group pgid()

2023-07-03 11:00 UTC, kmrdhruv commented on scripts/benchmark/README.md
> +
pip -r requirements.txt  ? needed ?

2023-07-04 17:01 UTC, kmrdhruv commented on scripts/benchmark/zk_benchmark.py
>          self.__measure(path, measure_samples, skip_measure)
nit: __measure_list()

2023-07-04 17:02 UTC, kmrdhruv approved these changes
LGTM.
Do execute the benchmark on a standard zk setup and publish results.

2023-07-05 08:53 UTC, aayustark007-fk commented on scripts/zk_benchmark.py
> +            for future in concurrent.futures.as_completed(futures_to_id):
So, I read that by using with statement will cause executor.shutdown() to be called which will terminate the processes. My assumption is that if I send a SIGINT via ctrl+c it should cause program to terminate and the with block to get cleaned up.

But, while running I see that when zookeeper becomes unreachable, the multiprocess program behaves badly. The program gets stuck and upon SIGTERM the main process exits but some of the processes continue to exists as zombies. (sending logs to the terminal)

2023-07-12 18:28 UTC, kmrdhruv approved these changes

2023-07-13 10:19 UTC, merged