produce flow code skeleton
flipkart-incubator/varadhi pull request #35
Opened 2023-07-25 06:03 UTC by kmrdhruv

Basic skeletion for produce flow.
Review primarily entities and code flow/pattern.

2023-07-27 11:18 UTC, gauravAshok commented on entities/src/main/java/com/flipkart/varadhi/entities/InternalTopic.java
> +        NotAllowed
rename to "Replicating".

2023-08-02 11:16 UTC, gauravAshok requested changes

2023-08-09 08:34 UTC, kmrdhruv commented on common/src/main/java/com/flipkart/varadhi/exceptions/ServerNotAvailableException.java
> +public class ServerNotAvailableException extends VaradhiException {
Agree, this is a candidate for refactoring. Will take it independently.

2023-08-09 08:36 UTC, kmrdhruv commented on common/src/main/java/com/flipkart/varadhi/utils/HeaderUtils.java
> +                .collect(Collectors.toMap(entry -> entry.getKey(), entry -> entry.getValue()));
i think in Varadhi, we work with first value ?

2023-08-09 13:38 UTC, kmrdhruv commented on server/src/main/java/com/flipkart/varadhi/RestVerticle.java
> +                });
This is to return response on the original context (event loop thread).

2023-08-09 16:19 UTC, kmrdhruv commented on messaging/src/main/java/com/flipkart/varadhi/produce/services/ProducerService.java
> +            String produceRegion = produceContext.getTopicContext().getRegion();
correct, likely to have same value for the deployment. Currently value is derived from the config at rest layer and passed down.

2023-08-09 16:50 UTC, kmrdhruv commented on entities/src/main/java/com/flipkart/varadhi/entities/ProduceContext.java
> +public class ProduceContext {
This is for transferring the rest api context to the actual produce layer, so mapped accordingly.

2023-08-09 16:53 UTC, kmrdhruv commented on entities/src/main/java/com/flipkart/varadhi/entities/InternalTopic.java
> +    public enum TopicStatus {
Not sure. At the moment it seems to contains both, Throttled(transient) vs blocked (persist-able).

2023-08-09 17:06 UTC, kmrdhruv commented on entities/src/main/java/com/flipkart/varadhi/entities/InternalTopic.java
> +        return String.format("%s.%s.%s", varadhiTopicName, InternalTopic.TopicKind.Main, region);
was thinking what would be better from search perspective when looking at global list ?
also this naming convention needs to be finalised w.r.to active/active, active/passive kind of scenarios.. TopicKind possibly can be avoided from it. -- let's discuss and close on this.

2023-08-09 17:20 UTC, kmrdhruv commented on entities/src/main/java/com/flipkart/varadhi/entities/ProduceResult.java
> +public class ProduceResult {
Possible candidate for removal is ProduceRestResult. It only contains messageId and that can be response itself.

2023-08-23 16:12 UTC, merged